Ticket import from csv file
CoderDojoBrianza/CoderDojo-Mobile-Toolbox pull request #12
Opened 2018-09-02 17:36 UTC by ercasta

Allows importing an external csv with tickets for an event. Participants are automatically created if not already in the DB

2018-09-04 20:19 UTC, sandrobonazzola requested changes

2018-09-04 20:19 UTC, sandrobonazzola commented on templates/coderdojomobile/eventTicketUpload.html
> +    <a href="{% url 'coderdojomobile:eventDetails' event.id %}"/>{% trans "Back to the event"%}</a>
here I see another terminated <a/>

2018-09-04 20:19 UTC, sandrobonazzola commented on templates/coderdojomobile/eventTicketUpload.html
> +{% endblock content %}
Line not terminated

2018-09-04 20:19 UTC, sandrobonazzola commented on views.py
> +                None
Please use "pass" if nothing to be done. I would have preferred to see some error on the screen.

2018-09-04 20:19 UTC, sandrobonazzola commented on views.py
> +            None
Please use "pass" and not None if nothing has to be done. I would prefer an error message.

2018-09-05 19:25 UTC, ercasta commented
Implemented requested changes

2018-11-26 21:23 UTC, sandrobonazzola approved these changes
Thanks!

2018-11-26 21:23 UTC, merged